using Xunit;

namespace SimpleNamespace.Tests
{
    class FirstClassTests
    {
        [Fact]
        public void FirstMethodTest()
        {
            Assert.True(false, "autogenerated");
        }

        [Fact]
        public void FirstMethod1Test()
        {
            Assert.True(false, "autogenerated");
        }
    }
}