using Xunit;

namespace Tests
{
    class ThirdClassTests
    {
        [Fact]
        public void ThirdMethodTest()
        {
            Assert.True(false, "autogenerated");
        }

        [Fact]
        public void ThirdMethod1Test()
        {
            Assert.True(false, "autogenerated");
        }
    }
}