using Xunit;

namespace Tests
{
    class SecondClassTests
    {
        [Fact]
        public void SecondMethodTest()
        {
            Assert.True(false, "autogenerated");
        }
    }
}